package Inventory;

public enum ItemType {
	BALL, 
	BAIT, 
	ROCK,
	STEP_POTION_SMALL,
	STEP_POTION_MEDIUM,
	STEP_POTION_LARGE,
	CAPTURE_POTION_SMALL,
	CAPTURE_POTION_MEDIUM,
	CAPTURE_POTION_LARGE,
	HEAL_POTION_SMALL,
	HEAL_POTION_MEDIUM,
	HEAL_POTION_LARGE;
}
